name: 'game_analytics'
version: '1.0.0'
config-version: 2

# This distinguishes "dev" schemas from "prod" schemas
profile: 'game_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # Directory which will store compiled SQL files
clean-targets:         # Directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

# Global configurations for your models
models:
  game_analytics:
    # Materialization strategy
    # 'view' is better for staging (lightweight)
    # 'table' is better for marts (performance)
    staging:
      +materialized: view
    marts:
      +materialized: table
