game_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      # CLEAN PATH!
      path: '/data_warehouse/game_analytics.duckdb'
      
      extensions:
        - httpfs
        - aws
      settings:
        s3_region: us-east-1
        s3_url_style: path
        s3_endpoint: "{{ env_var('MINIO_ENDPOINT', 'localhost:9000') }}"
        s3_access_key_id: "{{ env_var('MINIO_ROOT_USER', 'minioadmin') }}"
        s3_secret_access_key: "{{ env_var('MINIO_ROOT_PASSWORD', 'minioadmin') }}"
        s3_use_ssl: false
