output "storage_integration_name" {
  value = snowflake_storage_integration.s3_int.name
}

output "snowflake_iam_user" {
  description = "The IAM User ARN generated by Snowflake for this integration"
  value       = snowflake_storage_integration.s3_int.storage_aws_iam_user_arn
}

output "snowflake_external_id" {
  description = "The External ID generated by Snowflake for this integration"
  value       = snowflake_storage_integration.s3_int.storage_aws_external_id
}
